### ISSUE TITLE
Escape apostrophe

### ISSUE THREAD

**Issue by FansubDB** [FansubDB/fansubdb.github.io#17]
Some JSON have in their title a `'`, and the builder fails to load the data.
Yet we replace that by `&apos;` in the JSON file.

**Comment by KasaiDot** [comment]
Tu peut aussi remplacer le `'` par `/'` vu qu'apparament le code JSON est créé avec les `'`.

**Comment by fansub** [comment]
I think you speak about ```\'```?
If yes, Firefox can't escape that (```bad escaped character```) with JSON.parse

**Comment by KasaiDot** [comment]
Humm, en effet c'était bien `\'` ^^' faute de frappe.
Sinon, il reste l'option de changer tout les `'` du code JSON (`'tv':[{`) par des doubles `"`

**Comment by fansub** [comment]
If I understand, your idea is to remplace ```'``` by ```"```?
```{
	"name": "test""
}``` is not correct. We must to write ```{
	"name": "test\""
}```.
I didn't test to see if on firefox it's ok, but using ```&apos;``` instead of ```'``` and replace it in my js function like my [JS actually does seems to be better](https://github.com/fansub/fansub.github.io/blob/8071cc62cdb931e046df826c21810f2632a9c787/js/data.js#L23).

**Comment by KasaiDot** [comment]
Si tout fonctionne correctement comme ça autant laisser comme c'est pour l'instant...
à voir plus tard si on modifieras ou pas.

**Comment by KasaiDot** [comment]
Update : 
please update your ``{ "name": "test"" }`` by ``{ "name": "test" }`` and it will work.

**Comment by FansubDB** [comment]
I don't understand you. It's you who say to replace `'` by `"` [here](https://github.com/FansubDB/fansubdb.github.io/issues/17#issuecomment-162547085).

**Comment by KasaiDot** [comment]
Yeah, but it didn't notice but you made two ``"`` in the end >> ``{ "name": "test"**"** }``
Didn't know why did you add another ``"``.

**Comment by KasaiDot** [comment]
And for respond to that :
> ``{ "name": "test"" }`` is not correct. We must to write ``{ "name": "test\"" }``.
I didn't test to see if on firefox it's ok, but using ``&apos;`` instead of ``'`` and replace it in my js function like my JS actually does seems to be better.

If ``"test"\"`` won't work, i didn't know why ``'test''`` would work fine.

**Comment by FansubDB** [comment]
JSON file can't have `'` to delimitate the data. It must be `"`.
<br>So ```{ "test": "My Beautifull Title with ' in the end" }``` is correct but my parser can't parse it because of my code [here](https://github.com/FansubDB/fansubdb.github.io/blob/8071cc62cdb931e046df826c21810f2632a9c787/js/data.js#L161)

It's why I opened this issue :)

**Comment by KasaiDot** [comment]
Maybe you should leave that with the ``&apos;`` tag.

**Comment by FansubDB** [comment]
Resolved with https://github.com/FansubDB/fansubdb.github.io/commit/85dd054a731ca4839a356735f1b4a316f04b844c
