### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by FansubDB** [FansubDB/fansubdb.github.io#45]
To list contributing rules

**Comment by KasaiDot** [comment]
Something like this ?
``
1° : Fork this Repo
2° : Edit the file you want to edit in your repo.
3° : Test your release by downloading it and testing it on your favorite browser
4° : If no problems come, do a pull request for update in the official repo.
``

**Comment by FansubDB** [comment]
Not really, it's more for guidelines. It shows you a message like that: https://github.com/blog/1184-contributing-guidelines

**Comment by KasaiDot** [comment]
Okay, you do it ? or like always, the first who finish it do a pr?

**Comment by FansubDB** [comment]
No I'm doing it :-)
