### ISSUE TITLE
Add a CONTRIBUTORS.md

### ISSUE THREAD

**Issue by KasaiDot** [FansubDB/fansubdb.github.io#46]
Like the Issue #45 we should make a file where the contributors are displayed.
like :
``FansubDB (Owner)``
``...``

**Comment by FansubDB** [comment]
Not sure it's important.

You can see you [here](https://github.com/FansubDB/fansubdb.github.io/graphs/contributors)

**Comment by KasaiDot** [comment]
Well, it's not for me, but yes we can see it by the stats.
Closing it.

**Comment by FansubDB** [comment]
I'll do that :)

**Comment by FansubDB** [comment]
fixed https://github.com/FansubDB/fansubdb.github.io/commit/1202d7134215ed208f2f1e923ca4b2f775c6db17
