### ISSUE TITLE
MAL CDN | New Url

### ISSUE THREAD

**Issue by KasaiDot** [FansubDB/fansubdb.github.io#56]
I just view that, MyAnimeList changed the url for the pictures

Before the url should look like that: "http://cdn.myanimelist.net/images/anime/10/80312.jpg"
Now it's: "https://myanimelist.cdn-dena.com/images/anime/10/80312.jpg"

**Comment by FansubDB** [comment]
Thank you to report it, @KasaiDot

**Comment by KasaiDot** [comment]
No problem ;)
