### ISSUE TITLE
Suggestion | GH Files & Languages | v3

### ISSUE THREAD

**Issue by KasaiDot** [FansubDB/fansubdb.github.io#89]
Hi there, it's been a long time since i helped on this repo.

I have a new suggestion (like i always create)
- The "GH Files" like `CONTRIBUTING.md` & `CONTRIBUTORS.md` (not the README & the LICENCE files) can be placed on a new repo named `.github` github implement it since a while.
- The languages should be done via a file like `langs/fr.json` like:
```json
{
  "index_title": "Bonjour"
}
```
[...] who should be containing all the translation for the files. (so we don't need to create the same files when we want to add a new lang)

**Comment by FansubDB** [comment]
Hey, indeed @KasaiDot, welcome back :)

* About the languages, do you speak about #87 and #88?

I'm thinking about putting the translation in the https://github.com/FansubDB/data/blob/master/fr/list.json#L114

**Comment by KasaiDot** [comment]
Hi there, nope it's not the same.
I'll try to make it in the forked repo.
Wait a bit since i didn't have right now a laptop.

**Comment by FansubDB** [comment]
@KasaiDot , any news about this issue?

**Comment by KasaiDot** [comment]
Actually working on it, sorry for the delay.

- Kasai.
________________________________

**Comment by FansubDB** [comment]
Ok thank you :)

**Comment by KasaiDot** [comment]
Hi, i've been editing your code since 1month, but still not see how to update your code **AND** your data.
so i would'like to know if i can try to "redo" your repo (in my end).
Of course i'll include my askings in this version.

**Comment by FansubDB** [comment]
@KasaiDot any news about the issue?

**Comment by FansubDB** [comment]
:'(
